key_servers:
  - "0xa3b2c1d4e5f60718293a4b5c6d7e8f901112131415161718192a2b2c2d2e2f30"
  - "0xbcdef01234567890abcdeffedcba09876543211223344556677889900aabbcc"
public_keys:
  - "4f3c2d1eab8976cd5e4f3a2b1c0d9e8f7a6b5c4d3e2f1029384756a1b0cdef12"
  - "1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809"
package_id: "0xfedcba98765432100123456789abcdef0123456789abcdef0123456789abcd"
